# Generated by Django 4.1.3 on 2023-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_person_personfilmwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={"verbose_name": "Киножанр", "verbose_name_plural": "Киножанры"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Актер", "verbose_name_plural": "Актеры"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={"verbose_name": "Киноактер", "verbose_name_plural": "Киноактеры"},
        ),
        migrations.AddField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("tv_show", "tv_show"), ("movie", "movie")],
                default="",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
