# Generated by Django 4.1.3 on 2023-03-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_genrefilmwork_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"verbose_name": "FilmWork", "verbose_name_plural": "FilmWorks"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "GenreFilmWork",
                "verbose_name_plural": "GenreFilmWorks",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "Persons"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "Person/Filmwork",
                "verbose_name_plural": "Persons/Filmworks",
            },
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.CharField(
                default="", max_length=255, verbose_name="file_path"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateTimeField(verbose_name="creation date"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("tv_show", "tv_show"), ("movie", "movie")],
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="film_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.genre",
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="film_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.person",
                verbose_name="person",
            ),
        ),
    ]
