# Generated by Django 4.1.3 on 2023-03-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_filmwork_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
    ]
