# Generated by Django 4.1.3 on 2023-03-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_rename_created_genrefilmwork_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
