# Generated by Django 4.1.3 on 2023-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_rename_modified_at_filmwork_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateTimeField(null=True, verbose_name="creation date"),
        ),
    ]
