# Generated by Django 4.1.3 on 2023-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_filmwork_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("tv_show", "tv_show"), ("movie", "movie")],
                max_length=30,
                null=True,
                verbose_name="type",
            ),
        ),
    ]
