# Generated by Django 4.1.3 on 2023-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_filmwork_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="file_path",
            field=models.CharField(max_length=255, null=True, verbose_name="file_path"),
        ),
    ]
