# Generated by Django 4.1.3 on 2023-03-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_filmwork_description_alter_filmwork_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="film_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.genre",
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="film_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="film work",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.person",
                verbose_name="person",
            ),
        ),
    ]
