# Generated by Django 4.1.3 on 2023-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_genre_description_alter_genre_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("writer", "writer"),
                    ("director", "director"),
                ],
                max_length=255,
                null=True,
                verbose_name="role",
            ),
        ),
    ]
