# Generated by Django 3.2 on 2023-09-07 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('notifications', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                )
            ],
            options={'db_table': 'users"."user', 'managed': False},
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'UserGroup',
                'verbose_name_plural': 'UserGroups',
                'db_table': 'notifications"."user_group',
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='notifications.usergroup',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='notifications.user',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'verbose_name': 'UserGroupMembership',
                'verbose_name_plural': 'UserGroupMemberships',
                'db_table': 'notifications"."user_group_membership',
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='notifications.user'
            ),
        ),
    ]
