# Generated by Django 3.2 on 2023-09-13 10:47

import cronfield.models
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [('notifications', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField()),
            ],
            options={
                'db_table': 'notifications"."user',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UserGroup',
                'verbose_name_plural': 'UserGroups',
                'db_table': 'notifications"."user_group',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='body_editable',
            field=models.TextField(null=True, verbose_name='Template body'),
        ),
        migrations.AlterField(
            model_name='context',
            name='context_vars',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channels',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='cron_str',
            field=cronfield.models.CronField(
                default='* * * * *',
                help_text='Minute Hour Day Month Weekday',
                max_length=100,
                verbose_name='Cron',
            ),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='notification',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='notifications.notification',
            ),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='status',
            field=models.CharField(
                choices=[('stale', 'To be deleted'), ('pending', 'Pending')],
                default='pending',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_disabled',
            field=models.JSONField(verbose_name='No email for them'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mime_type',
            field=models.CharField(
                choices=[('text/html', 'HTML'), ('text/plain', 'Text')],
                max_length=255,
                verbose_name='Template media type',
            ),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Template name'),
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='notifications.usergroup',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='notifications.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'UserGroupMembership',
                'verbose_name_plural': 'UserGroupMemberships',
                'db_table': 'notifications"."user_group_membership',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='notifications.usergroup',
            ),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='notifications.user',
            ),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='notifications.user'
            ),
        ),
    ]
