# Generated by Django 3.2 on 2023-09-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('notifications', '0002_user_groups')]

    operations = [migrations.AlterModelOptions(name='user', options={'managed': False})]
