# Generated by Django 3.2 on 2023-09-09 09:44

import cronfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_context_context_vars_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='context_vars_editable',
            field=models.TextField(null=True, verbose_name='Context vars'),
        ),
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='cron_str',
            field=cronfield.models.CronField(default='* * * * *', help_text='Minute Hour Day Month Weekday', max_length=100, verbose_name='Cron'),
        ),
    ]
