# Generated by Django 3.2 on 2023-09-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20230910_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body_editable',
            field=models.TextField(null=True, verbose_name='Template body'),
        ),
    ]
