# Generated by Django 3.2 on 2023-09-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('notifications', '0009_alter_template_body_editable')]

    operations = [
        migrations.AlterField(
            model_name='eventnotification',
            name='event',
            field=models.CharField(
                choices=[('registered', 'Registered')], max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='notification',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='notifications.notification',
            ),
        ),
        migrations.AlterField(
            model_name='notificationcron',
            name='status',
            field=models.CharField(
                choices=[('stale', 'To be deleted'), ('pending', 'Pending')],
                default='pending',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='template',
            name='mime_type',
            field=models.CharField(
                choices=[('text/html', 'HTML'), ('text/plain', 'Text')],
                max_length=255,
                verbose_name='Template media type',
            ),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default',
            field=models.CharField(choices=[('email', 'Email')], max_length=255),
        ),
    ]
