# Generated by Django 3.2 on 2023-09-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('notifications', '0010_auto_20230911_1907')]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='notifications.user',
            ),
        )
    ]
