# Generated by Django 3.2 on 2023-09-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('movies', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={
                'verbose_name': 'GenreFilmWork',
                'verbose_name_plural': 'GenreFilmWorks',
            },
        )
    ]
