# Generated by Django 3.2 on 2023-10-03 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AcquiringLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'transaction_id',
                    models.TextField(null=True, verbose_name='transaction_id'),
                ),
                (
                    'invoice_id',
                    models.UUIDField(
                        default=uuid.uuid4, null=True, verbose_name='invoice_id'
                    ),
                ),
                (
                    'transaction_type',
                    models.CharField(
                        max_length=20, null=True, verbose_name='transaction_type'
                    ),
                ),
                ('acq_message', models.TextField(null=True, verbose_name='acq_error')),
                ('acq_code', models.IntegerField(null=True, verbose_name='acq_code')),
                (
                    'acq_provider',
                    models.TextField(null=True, verbose_name='acq_provider'),
                ),
            ],
            options={
                'verbose_name': 'AcquiringLog',
                'verbose_name_plural': 'AcquiringLogs',
                'db_table': 'payments"."acq_status_log',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True, verbose_name='amount')),
                (
                    'currency',
                    models.CharField(max_length=3, null=True, verbose_name='currency'),
                ),
                (
                    'transaction_id',
                    models.TextField(null=True, verbose_name='transaction_id'),
                ),
                (
                    'status',
                    models.CharField(max_length=20, null=True, verbose_name='status'),
                ),
                (
                    'user_id',
                    models.UUIDField(
                        default=uuid.uuid4, null=True, verbose_name='user_id'
                    ),
                ),
                (
                    'subscription_id',
                    models.UUIDField(
                        default=uuid.uuid4, null=True, verbose_name='subscription_id'
                    ),
                ),
                (
                    'acquiring_provider',
                    models.TextField(null=True, verbose_name='acquiring_provider'),
                ),
                (
                    'payment_type',
                    models.CharField(max_length=20, null=True, verbose_name='currency'),
                ),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'payments"."invoice',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True, verbose_name='amount')),
                (
                    'currency',
                    models.CharField(max_length=3, null=True, verbose_name='currency'),
                ),
                (
                    'transaction_id',
                    models.TextField(null=True, verbose_name='transaction_id'),
                ),
                (
                    'status',
                    models.CharField(max_length=20, null=True, verbose_name='status'),
                ),
                (
                    'invoice_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='billing.invoice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'payments"."refund',
            },
        ),
    ]
