# Generated by Django 3.2 on 2023-10-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('billing', '0001_initial')]

    operations = [
        migrations.RenameField(
            model_name='invoice', old_name='updated_at', new_name='modified_at'
        ),
        migrations.RenameField(
            model_name='refund', old_name='updated_at', new_name='modified_at'
        ),
    ]
